spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shopping_online
    username: springstudent
    password: springstudent
  jpa:
    hibernate:
      ddl-auto: 'update'
    show-sql: true
    generate-ddl: true
  main:
    banner-mode: false
logging:
  level:
    root: warn





